# --- SQLite JDBC ---
spring.datasource.url=jdbc:sqlite:SeenIt.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

# --- Hibernate + JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecte personalitzat (el teu)
spring.jpa.database-platform=org.example.proyectofinal.config.SQLiteDialect
spring.jpa.properties.hibernate.dialect=org.example.proyectofinal.config.SQLiteDialect

# --- Desactivar servidor web (important per JavaFX) ---
spring.main.web-application-type=none
